// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

// Injectors from wire.go:

func initEsim() *Esim {
	config := provideConf()
	logger := provideLogger(config)
	prome := provideProme(config, logger)
	esim := &Esim{
		prome: prome,
		Log:   logger,
		Conf:  config,
	}
	return esim
}

func NewMockEsim() *Esim {
	config := provideMockConf()
	prome := provideMockProme(config)
	logger := provideLogger(config)
	esim := &Esim{
		prome: prome,
		Log:   logger,
		Conf:  config,
	}
	return esim
}
