// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jukylin/esim/tool/db2entity/example/entity"
	mock "github.com/stretchr/testify/mock"
)

// TestHistoryRepo is an autogenerated mock type for the TestHistoryRepo type
type TestHistoryRepo struct {
	mock.Mock
}

// FindById provides a mock function with given fields: _a0, _a1
func (_m *TestHistoryRepo) FindById(_a0 context.Context, _a1 int64) entity.TestHistory {
	ret := _m.Called(_a0, _a1)

	var r0 entity.TestHistory
	if rf, ok := ret.Get(0).(func(context.Context, int64) entity.TestHistory); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.TestHistory)
	}

	return r0
}
