// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// FindById provides a mock function with given fields: _a0
func (_m *Repo) FindById(_a0 int) {
	_m.Called(_a0)
}
